/*
 * This file is generated by jOOQ.
 */
package com.example.genealogyback.jooq;


import com.example.genealogyback.jooq.tables.Persons;
import com.example.genealogyback.jooq.tables.records.PersonsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PersonsRecord> PK_PERSONS_UUID = Internal.createUniqueKey(Persons.PERSONS, DSL.name("pk_persons_uuid"), new TableField[] { Persons.PERSONS.ID }, true);
}
