/*
 * This file is generated by jOOQ.
 */
package com.example.genealogyback.jooq;


import com.example.genealogyback.jooq.tables.Persons;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * Информация о людях.
     */
    public static final Persons PERSONS = Persons.PERSONS;
}
